#!/usr/bin/bash
pip --version

# Criar ambiente Virtual

python3 -m virtualenv my_env

# Acessar o ambiente Virtual

source my_env/bin/activate

pip install -t local_lib --log logfile.log git+https://github.com/jaraco/path.git --force-reinstall --upgrade

python3 my_program.py

# Instalar o Django

pip install django

#Criar projeto 

django-admin startproject Nome_do_projeto

#criar aplicação

python manage.py startapp Nome_doApp

#iniciar o servidor 

python3 manage.py runserver